### ISSUE TITLE
transfer website ownership

### ISSUE THREAD

**Issue by WEGFan** [Mygod/edgefans-archive#17]
我把repo fork过去后用github建了个 https://edgefans.github.io ，以后要更新的话我直接在github上改代码就行了，也不用发pr

**Comment by Mygod** [comment]
It's actually on edgefans.mygod.be already.

**Comment by WEGFan** [comment]
处理不想处理的pr不觉得麻烦吗

**Comment by Mygod** [comment]
It's hosted on GitHub with CloudFlare as CDN.
